### ISSUE TITLE
A way to contribute

### ISSUE THREAD

**Issue by zperk13** [zeskeertwee/destiny-rs#1]
I started writing my own library like this one, then I found this, and it's done very similarly to how I was doing it (reqwest+serde/serde_json). I wanted to help update this with the new changes to the api. A way to contribute changes would be nice.

**Comment by zeskeertwee** [comment]
Thank you for wanting to contribute!
I have added a section to the README about contributing.
You should know that this library currently does not cover all API endpoints and structs, but that is the eventual goal.
