### ISSUE TITLE
Hash type

### ISSUE THREAD

**Issue by zeskeertwee** [zeskeertwee/destiny-rs#3]
It would be very interesting to implement a hash type that contains the type it'd get from the manifest (e.g. `Hash<Race>`) which would allow for easier interaction with the manifest, and prevent type issues when doing so.

**Comment by zperk13** [comment]
But when you get a hash, isn't it just a hash, not contained it's dehashed version? If I'm wrong about that, it might be as simple as

```rust
struct Hash<T> {
    hash: Uint32,
    value: T
}
```

**Comment by zeskeertwee** [comment]
That would be a way to do it, but that wasn't my original idea, because this way you'd need the manifest when doing queries that return a Hash. The original idea i had was to have the return type in a PhantomType alongside with the Uint, and add a function so that you could query it from the manifest, automatically inferring the correct return type.
