### ISSUE TITLE
user::GeneralUser::context ready to get a PR

### ISSUE THREAD

**Issue by zperk13** [zeskeertwee/destiny-rs#6]
I saw a TODO comment in user::GeneralUser to add the context value to the struct, so I did along with it's corresponding struct, the UserToUserContext, and with one of it's value's sturcts, the IgnoreResponse. I'll be able to make a PR for it once PR #4  is merged.

If you care, here's the branch that will be in the PR: https://github.com/zperk13/destiny-rs/tree/user_context

**Comment by zeskeertwee** [comment]
I've merged PR #4, but I can't open a PR on mobile apparently.

**Comment by zperk13** [comment]
Thanks! PR #7 is now ready

**Comment by zeskeertwee** [comment]
Thanks!
