### ISSUE TITLE
"mapped to" confusion

### ISSUE THREAD

**Issue by zperk13** [zeskeertwee/destiny-rs#8]
I'm working on adding the missing properties to models::manifest_models::InventoryItem, and there's a lot of hashes. What I'm confused about is in the bungie docs, it says it's mapped to it's own type/object, but the hashes that are already there in the code are saying they're mapped to a varient of the models::manifest::ManifestKey enum with the same name.

Eg:
```rust
/// mapped to [`Collectible`](crate::models::manifest::ManifestKey::Collectible)
pub collectible_hash: Option<Hash>,
```
but the docs say collectible_hash is a hash of https://bungie-net.github.io/multi/schema_Destiny-Definitions-Collectibles-DestinyCollectibleDefinition.html#schema_Destiny-Definitions-Collectibles-DestinyCollectibleDefinition which is it's own type

**Comment by zeskeertwee** [comment]
The manifest key is used to map the hash to the correct table here, in this case that'd be the DestinyCollectibleDefinitions table, and the type a query retuns is Collectible (called DestinyCollectibleDefinition in bungie's docs)

**Comment by zperk13** [comment]
Will the "mapped to" comments always point to a variant of models::manifest::ManifestKey?

**Comment by zeskeertwee** [comment]
Yes, that's correct.
